// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApplication.DataAccess.Context;

#nullable disable

namespace QuizApplication.DataAccess.Migrations.Development
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuizApplication.DataAccess.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParticipationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("QuizApplication.DataAccess.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Choises")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CorrectOptions")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Choises = "[\"Option 1\",\"Option 2\",\"Option 3\",\"Option 4\"]",
                            CorrectOptions = "[\"Option 2\"]",
                            Points = 1,
                            Title = "Question 1"
                        },
                        new
                        {
                            Id = 2,
                            Choises = "[\"Option 1\",\"Option 2\",\"Option 3\",\"Option 4\"]",
                            CorrectOptions = "[\"Option 1\",\"Option 3\"]",
                            Points = 1,
                            Title = "Question 2"
                        },
                        new
                        {
                            Id = 3,
                            Choises = "[\"Option 1\",\"Option 2\",\"Option 3\",\"Option 4\"]",
                            CorrectOptions = "[\"Option 4\"]",
                            Points = 1,
                            Title = "Question 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
